name: pentaho-data-integration-spicule
version: '8.0'
summary: Pentaho Data Integration Server
description: |
    Data Integration Server which allows users to ingest data into a variety
    of platforms via a GUI for CLI

grade: stable
confinement: strict

apps:
  spoon:
    command: desktop-launch $SNAP/data-integration/spoon.sh
    plugs: [network, network-bind,x11,home]

  kitchen:
    command: data-integration/kitchen.sh
    plugs: [network, network-bind]

  pan:
    command: data-integration/pan.sh
    plugs: [network,network-bind]

  carte:
    command: data-integration/carte.sh $SNAP_DATA/carte-config.xml
    plugs: [network,network-bind]
    daemon: simple

  encrypt:
    command: data-integration/encr.sh
    plugs: [network,network-bind]

parts:
  data-integration:
    plugin: x_maven
    source: https://github.com/pentaho/pentaho-kettle.git
    source-type: git
    source-branch: 8.0.0.0
    maven-options: [-DskipTests]
    stage-packages: ["unzip"]
    build-packages: ["libwebkitgtk-1.0-0"]
    install: |
        unzip $SNAPCRAFT_PART_INSTALL/zip/pdi-ce-8.0-SNAPSHOT.zip -d $SNAPCRAFT_PART_INSTALL/
        rm -rf $SNAPCRAFT_PART_INSTALL/zip/pdi-ce-8.0-SNAPSHOT.zip
    after: [desktop-gtk3]
    stage:
        - -data-integration/spoon.sh
        - -data-integration/launcher/launcher.properties
  data-customizations:
        plugin: copy
        files:
            src/pdi/spoon.sh: data-integration/
            src/pdi/launcher.properties: data-integration/launcher/
