name: pentaho-data-integration-spicule
version: '8.0'
summary: Data Integration Server
description: |
    Data Integration Server which allows users to ingest data into a variety
    of platforms via a GUI for CLI.

grade: devel
confinement: devmode

apps:
  spoon:
    command: data-integration/spoon.sh
    plugs: [network, network-bind]

parts:
  data-integration:
    plugin: x_maven
    source: https://github.com/pentaho/pentaho-kettle.git
    source-type: git
    source-branch: 8.0.0.0
    maven-options: [-DskipTests]
    install: |
        unzip $SNAPCRAFT_PART_INSTALL/zip/pdi-ce-8.0-SNAPSHOT.zip -d $SNAPCRAFT_PART_INSTALL/
